variable "instance_type" {}
variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "ami" {}
variable "instance_name" {}
variable "cidr_block" {}
variable "vpc_name" {}
variable "pub_subnetA_az" {}
variable "pub_subnetB_az" {}
variable "pub_subnetA_name" {}
variable "pub_subnetB_name" {}
variable "security_groups_name" {}
variable "instance_A_name" {}
variable "instance_B_name" {}
variable "igw_name" {}
variable "route_table_name" {}
variable "key_name" {}
